### ISSUE TITLE
ZeroDivisionError: float division by zero in detect_iris

### ISSUE THREAD

**Issue by llinjupt** [antoinelame/GazeTracking#7]
@antoinelame  THX for your awesome job first. But when I try example.py the log gives me the error:

`Traceback (most recent call last):
  File "example.py", line 18, in <module>
    gaze.refresh(frame)
  File "C:\Users\Red\.spyder\dolist\pyimage\GazeTracking\gaze_tracking\gaze_tracking.py", line 64, in refresh
    self._analyze()
  File "C:\Users\Red\.spyder\dolist\pyimage\GazeTracking\gaze_tracking\gaze_tracking.py", line 51, in _analyze
    self.eye_right = Eye(frame, landmarks, 1, self.calibration)
  File "C:\Users\Red\.spyder\dolist\pyimage\GazeTracking\gaze_tracking\eye.py", line 22, in __init__
    self._analyze(original_frame, landmarks, side, calibration)
  File "C:\Users\Red\.spyder\dolist\pyimage\GazeTracking\gaze_tracking\eye.py", line 112, in _analyze
    self.pupil = Pupil(self.frame, threshold)
  File "C:\Users\Red\.spyder\dolist\pyimage\GazeTracking\gaze_tracking\pupil.py", line 17, in __init__
    self.detect_iris(eye_frame)
  File "C:\Users\Red\.spyder\dolist\pyimage\GazeTracking\gaze_tracking\pupil.py", line 51, in detect_iris
    self.x = int(moments['m10'] / moments['m00'])
ZeroDivisionError: float division by zero`

OpenCV 3.1.0.  BTW  in eye.py line 86 may have the same issue, but I can't repeat it again and so the log lost.

**Comment by antoinelame** [comment]
Hi @llinjupt 
Well spotted, thank you! I fixed it
