### ISSUE TITLE
code start issue.

### ISSUE THREAD

**Issue by Rohit2111** [antoinelame/GazeTracking#79]
python3 example.py 
Traceback (most recent call last):
  File "/home/admin1/Desktop/GazeTracking-master/example.py", line 17, in <module>
    gaze.refresh(frame)
  File "/home/admin1/Desktop/GazeTracking-master/gaze_tracking/gaze_tracking.py", line 63, in refresh
    self._analyze()
  File "/home/admin1/Desktop/GazeTracking-master/gaze_tracking/gaze_tracking.py", line 44, in _analyze
    frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by YINGXINYAN** [comment]
I have the same problem, did you solve it ? Help Please

**Comment by Sponge-bo** [comment]
me too,thanks!
