### ISSUE TITLE
I had a error“RuntimeError: Error deserializing object of type int”

### ISSUE THREAD

**Issue by Fnckerpoi** [antoinelame/GazeTracking#9]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/GazeTracking-master/example.py", line 9, in <module>
    gaze = GazeTracking()
  File "C:\Users\Administrator\Desktop\GazeTracking-master\gaze_tracking\gaze_tracking.py", line 28, in __init__
    self._predictor = dlib.shape_predictor(model_path)
RuntimeError: Error deserializing object of type int

**Comment by antoinelame** [comment]
Hi @Fnckerpoi 
Your `shape_predictor_68_face_landmarks.dat` file is corrupted. Re-download it and check that the md5 checksum of the file is: 73fde5e05226548677a050913eed4e04
